# Generated by Django 4.2.3 on 2023-07-14 06:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('places', models.CharField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_owner', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ui_elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(upload_to='ui_bac_image/')),
                ('header', models.ImageField(upload_to='ui_png/')),
                ('ico_header', models.ImageField(upload_to='ico_header/')),
                ('f_image', models.ImageField(upload_to='f_image/')),
                ('complete_image', models.ImageField(blank=True, upload_to='complete_image/')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_restaurant', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=25)),
                ('rating', models.IntegerField()),
                ('about', models.TextField(max_length=400)),
                ('terrace_restaurant', models.CharField(max_length=11)),
                ('parking_restaurant', models.CharField(max_length=11)),
                ('kitchen', models.CharField(max_length=20)),
                ('average_check', models.IntegerField()),
                ('photo_restaurant', models.ImageField(upload_to='photo_restaurant/')),
                ('photo_restaurant2', models.ImageField(upload_to='second_photo_restaurant/')),
                ('photo_restaurant3', models.ImageField(upload_to='third_photo_restaurant/')),
                ('menu', models.ImageField(upload_to='menu_img/')),
                ('menu_download', models.FileField(upload_to='media/menu/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('conn', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res', to='app.owner')),
            ],
        ),
    ]
