# Generated by Django 4.2.3 on 2023-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui_elements',
            name='ico_setting_header',
            field=models.ImageField(null=True, upload_to='ico_header/'),
        ),
    ]
