# Generated by Django 4.2.3 on 2023-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ui_elements_ico_setting_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='ui_elements',
            name='edit_restaurant_setting_img',
            field=models.ImageField(blank=True, upload_to='setting_img/'),
        ),
        migrations.AddField(
            model_name='ui_elements',
            name='new_restaurant_setting_img',
            field=models.ImageField(blank=True, upload_to='setting_img/'),
        ),
        migrations.AddField(
            model_name='ui_elements',
            name='support_setting_img',
            field=models.ImageField(blank=True, upload_to='setting_img/'),
        ),
        migrations.AddField(
            model_name='ui_elements',
            name='user_setting_img',
            field=models.ImageField(blank=True, upload_to='setting_img/'),
        ),
    ]
