# Generated by Django 4.2.3 on 2023-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ui_elements_edit_restaurant_setting_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_new_restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new_restaurant', models.CharField(max_length=15)),
                ('blank', models.FileField(upload_to='documents_owner')),
                ('document1', models.FileField(upload_to='documents_owner')),
                ('document2', models.FileField(upload_to='documents_owner')),
                ('document3', models.FileField(upload_to='documents_owner')),
            ],
        ),
    ]
