# Generated by Django 4.2.3 on 2023-08-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_application_new_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text_1', models.CharField(max_length=240, null=True)),
                ('info_text_2', models.CharField(max_length=240, null=True)),
                ('info_text_3', models.CharField(max_length=240, null=True)),
                ('info_text_4', models.CharField(max_length=240, null=True)),
                ('info_text_5', models.CharField(max_length=240, null=True)),
                ('info_text_6', models.CharField(max_length=240, null=True)),
                ('info_text_7', models.CharField(max_length=240, null=True)),
                ('info_text_8', models.CharField(max_length=240, null=True)),
                ('info_text_9', models.CharField(max_length=240, null=True)),
            ],
        ),
    ]
