# Generated by Django 4.2.3 on 2023-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_info_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_text',
            name='info_text_1',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_2',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_3',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_4',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_5',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_6',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_7',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_8',
            field=models.TextField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_9',
            field=models.TextField(max_length=240, null=True),
        ),
    ]
