# Generated by Django 4.2.3 on 2023-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_info_text_info_text_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_3',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_4',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_5',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_6',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_7',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_8',
        ),
        migrations.RemoveField(
            model_name='info_text',
            name='info_text_9',
        ),
        migrations.AlterField(
            model_name='info_text',
            name='info_text_2',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
