# Generated by Django 4.2.3 on 2023-08-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_info_text_info_text_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_text',
            name='info_text_1',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
