# Generated by Django 4.2.3 on 2023-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_info_text_info_text_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu_download',
            field=models.FileField(upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
