# Generated by Django 4.2.3 on 2023-08-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_restaurant_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='publication',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
