# Generated by Django 4.2.3 on 2023-08-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='Message',
        ),
    ]
