# Generated by Django 4.2.3 on 2023-08-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_message_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.TextField(max_length=400),
        ),
    ]
