# Generated by Django 4.2.3 on 2023-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_restaurant_owner_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu_download',
            field=models.FileField(null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo_restaurant',
            field=models.ImageField(null=True, upload_to='photo_restaurant/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo_restaurant2',
            field=models.ImageField(null=True, upload_to='second_photo_restaurant/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='photo_restaurant3',
            field=models.ImageField(null=True, upload_to='third_photo_restaurant/'),
        ),
    ]
