# Generated by Django 4.2.3 on 2023-08-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_request_token_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='about',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
