# Generated by Django 4.2.3 on 2023-08-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_restaurant_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_message',
            name='datetime',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
