# Generated by Django 4.2.3 on 2023-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_support_message_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
