# Generated by Django 4.2.3 on 2023-08-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_support_message_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_token',
            name='date_request',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
