# Generated by Django 4.2.3 on 2023-08-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_request_token_date_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_token',
            name='date_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='support_message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
