# Generated by Django 4.2.3 on 2023-08-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_application_new_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_new_restaurant',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
