# Generated by Django 4.2.3 on 2023-08-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_application_new_restaurant_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_new_restaurant',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
